python compute.py --task bace
python compute.py --task bear
python compute.py --task clintox
python compute.py --task diblock
python compute.py --task electro
python compute.py --task esol
python compute.py --task free
python compute.py --task glotzer_pf
python compute.py --task glotzer_xa
python compute.py --task hiv
python compute.py --task hplc
python compute.py --task lipo
python compute.py --task muv
python compute.py --task oer
python compute.py --task oxidation
python compute.py --task perovskite
python compute.py --task polygel
python compute.py --task polysol
python compute.py --task princeton
python compute.py --task qm9_cv
python compute.py --task qm9_gap
python compute.py --task qm9_r2
python compute.py --task qm9_u0
python compute.py --task qm9_zpve
python compute.py --task robeson
python compute.py --task shower
python compute.py --task toporg
python compute.py --task tox21
python compute.py --task vdw
python compute.py --task water_hp
python compute.py --task water_lp
